services:
  ghp:
    image: ruby:3.3-slim
    volumes:
    - .:/app
    - bundle:/usr/local/bundle
    working_dir: /app
    ports:
    - 4000:4000
    command:
      - /bin/sh
      - -c
      - |
        apt-get update -qq && apt-get install -y -qq build-essential git > /dev/null
        git config --global --add safe.directory /app
        gem install bundler -v 2.3.25 --no-document -q
        bundle install
        bundle exec jekyll serve --host 0.0.0.0

volumes:
  bundle:
